### ISSUE TITLE
mapply error: 'zero-length inputs cannot be mixed with those of non-zero length'

### ISSUE THREAD

**Issue by TessaGillett** [thomasp85/mzID#32]
Hi,

I'm having the same problem as is reported in #31 , which I don't think was ever solved. I've commented there, but later realised that since it's closed that probably doesn't result in any notifications, so I'm sorry for the duplication! 

At any rate: when I try to parse a .mzid file, after a short wait I get the following error. (In #31 it's said that took about 10 hrs, in my case it's usually a few minutes.)

`Error in mapply(sub, paste("^\\Q", database$accession[hasRightName], "\\E", : zero-length inputs cannot be mixed with those of non-zero length`

I've had a look to compare my files to the example .mzid files, but as I'm relatively unexperienced with the format I'm not sure where the problem originates. Any idea what might be causing this?

Thank you!
Tessa

**Comment by lgatto** [comment]
Hi @TessaGillett - could you provide the output of `sessionInfo()` and share the file so that I can try to reproduce the error.

**Comment by TessaGillett** [comment]
This is the `sessionInfo() `output:

```
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.2

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] nl_NL.UTF-8/nl_NL.UTF-8/nl_NL.UTF-8/C/nl_NL.UTF-8/nl_NL.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mzID_1.20.1

loaded via a namespace (and not attached):
 [1] compiler_3.5.2      plyr_1.8.4          ProtGenerics_1.14.0 parallel_3.5.2      tools_3.5.2         yaml_2.2.0         
 [7] Rcpp_1.0.0          codetools_0.2-16    doParallel_1.0.14   iterators_1.0.10    foreach_1.4.4       XML_3.98-1.16      
```

Do you have an address I can send the file to? I think it's too big to add here.

**Comment by lgatto** [comment]
No, I don't wish to get it by email. You can post it on dropbox, google drive, an ftp server, ... and post the link here, so that I can download it.

**Comment by TessaGillett** [comment]
In that case, here it is: https://we.tl/t-FxlzSOPy8h
Thanks again for the help!

**Comment by lgatto** [comment]
Thanks, got it.

**Comment by lgatto** [comment]
Could you try re-installing with 
```r
BiocManager::install("thomasp85/mzID")
```
Generating the `mzID` object should work now, although I haven't checked if any downstream operations still work as expected.

**Comment by TessaGillett** [comment]
Hi Laurent, I re-installed the package, but I'm still having the same problem I'm afraid.

**Comment by lgatto** [comment]
Have you restarted your R session?

**Comment by TessaGillett** [comment]
Yes, I'm afraid so. Deleted the package in the terminal directly as it wasn't actually removed with `remove.packages()` (installed under a different R version), then checked to make sure it wasn't working anymore, re-installed and restarted my session.

**Comment by lgatto** [comment]
Sorry, I thought I had pushed. It should be ok now:
```r
> x <- mzID("./mod_TT1_111130_TY_BN3_LysC_SCX_20percent_F20_recal_371_445_searchgui_out.mzid")
reading mod_TT1_111130_TY_BN3_LysC_SCX_20percent_F20_recal_371_445_searchgui_out.mzid... DONE!
> x
An mzID object

Software used:   PeptideShaker (version: 1.16.36)

Rawfile:         file:/home/tessa/Proteomics_data/PXD000131/mgfFiles/node_none/lysC/mod_TT1_111130_TY_BN3_LysC_SCX_20percent_F20_recal_371_445.mgf

Database:        file:/home/tessa/analysisRat/out/seqDB/multiSampleDB_uniqueIDs_concatenated_target_decoy.fasta

Number of scans: 27768
Number of PSM's: 27768
> sessionInfo()
R version 3.5.3 Patched (2019-03-11 r76221)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/libf77blas.so.3.10.3
LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mzID_1.21.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1          magrittr_1.5        doParallel_1.0.14  
 [4] R6_2.4.0            foreach_1.4.4       plyr_1.8.4         
 [7] tools_3.5.3         pkgbuild_1.0.3      parallel_3.5.3     
[10] cli_1.1.0           withr_2.1.2         ProtGenerics_1.14.0
[13] iterators_1.0.10    remotes_2.0.4       assertthat_0.2.1   
[16] rprojroot_1.3-2     crayon_1.3.4        processx_3.3.0     
[19] BiocManager_1.30.4  callr_3.2.0         ps_1.3.0           
[22] codetools_0.2-16    curl_3.3            compiler_3.5.3     
[25] backports_1.1.4     prettyunits_1.0.2   XML_3.98-1.19      
```

**Comment by TessaGillett** [comment]
It does, thank you for the help!
